@startuml
' !pragma useVerticalIf off

start
skinparam activitybackgroundcolor #ffffff
skinparam activitydiamondbackgroundcolor #ffffff
skinparam activitydiamondbordercolor #000000
skinparam activitybordercolor #000000
skinparam arrowcolor #000000
skinparam shadowing false

if (percent >= 75) then (True)
    :print("great");
endif

if (percent >= 50) then (True)
    :print("good");
endif

if (percent < 50) then (True)
    :print("fair");
endif

stop
@enduml
